### ISSUE TITLE
Circular dependency that doesn't exist

### ISSUE THREAD

**Issue by CarlOlson** [rescript-lang/rewatch#128]
I tried `rewatch` in a large monorepo and got an non-existent circular dependency error.

The code looks like this:

- ProjectFrontend `namespace: false`
  - Server
  - Component
  - Api
  - Context
- ProjectBackend `namespace: true`
  - UnrelatedModule
    - Make Functor
      - module Server = ...

`Component` -> `Api` -> `ProjectBackend.UnrelatedModule` -> `Server` -> `Api`

`ProjectFrontend` uses types from `ProjectBackend`, but not from `UnrelatedModule`. It appears that it is mixing up the `Server` module inside the functor with `Server` module in `ProjectFrontend`.

I believe it has to do with the `namespace` option. Changing `ProjectFrontend` to `namespace: true` results in different errors that are fixable.

**Comment by rolandpeelen** [comment]
@CarlOlson -- This could very well be the namespace indeed. If they aren't enabled, module names are treated globally. Rewatch essentially compiles your monorepo as a single massive project. Think of it as having a single root `rescript.json` that orchestrates everything in a single build rather than a bunch of smaller projects that compile separately. So in the 'old' style, it would be fine compiling the smaller units as they are separate `rescript` projects. So `Server` in Frontend doesn't know `Server` in Backend exists. But with Rewatch it's a single big project, so they do know both exist. So enabling `namespace: true` is the way to go here.

Feel free to re-open the issue if you have questions :)
