### ISSUE TITLE
Feature Request: Verbose Command Output

### ISSUE THREAD

**Issue by Bushuo** [rescript-lang/rewatch#137]
While working on #102, I found it helpful to see the output of `bsc`. I think it would be a great addition to have a command line flag in Rewatch that allows users to view the output of the underlying commands, something like:
```
rewatch build --verbose
```
I'd be happy to submit a PR for this if you're open to it.

**Comment by rolandpeelen** [comment]
@Bushuo - A PR would be super welcome here. I've done [some work here](https://github.com/rescript-lang/rewatch/pull/126) to move to `env:logger` but my time is slipping away from me. Perhaps you can take that as a starting point and implement @cknitt 's comment to instantiate the logger from an argument rather than from env?

**Comment by rolandpeelen** [comment]
Done here: https://github.com/rescript-lang/rewatch/pull/126

-- We should add some debug / trace logs throughout the code for better verbosity, including for instance the commands we're running to bsc. I have some thoughts on restructuring a thing or two to make this better, including error handling. Consider it a work in progress. 

Closing this for now - Feel free to open a PR if you see a place you'd like some trace output :)

**Comment by Bushuo** [comment]
@rolandpeelen - Thanks for picking this back up. I unfortunately did not have time for this the last weeks. I will take a look at your PR and maybe provide a PR myself for logging the commands to bsc that you mentioned.
